-- 201 · DB-019 / DB-020 第一批（分批迁移 1/N）。
-- （文件曾名 199_db019_db020_batch1.sql，注册版本一直是 201；改名只为让编号一致，
--   本行注释同步 —— 只动注释，SQL 语句与幂等判据未变。）
--
-- 决策（YG 拍板）：
--   DB-019：时间列统一为 create_time（放弃 created_at）；
--   DB-020：主键统一为 BIGSERIAL（bigint identity），软删列名随后续批次统一。
--
-- 本批对象（零入度叶子表，无数据库层外键引用其 id，回填风险最小）：
--   build_jobs / blocks / page_site_slots / publication_receipts / inventory_change_reasons
-- 连带：inventory_stock_movements.reason_id（逻辑引用，无 DB 约束）随 reasons.id 一起改类型。
-- 五张表现有数据均为 0 行，回填 UPDATE 仅作为防御性逻辑保留（可重放）。
-- 相关索引（含 idx_build_jobs_claim 这类基于 created_at 的部分索引）不包含 id 列，
-- RENAME 后 Postgres 自动跟随列名，无需重建。

-- ========== build_jobs ==========
ALTER TABLE build_jobs ADD COLUMN IF NOT EXISTS id_new bigint GENERATED BY DEFAULT AS IDENTITY;
UPDATE build_jobs SET id_new = s.rn
  FROM (SELECT id, row_number() OVER (ORDER BY created_at) AS rn FROM build_jobs) s
  WHERE build_jobs.id = s.id AND build_jobs.id_new IS NULL;
ALTER TABLE build_jobs DROP CONSTRAINT build_jobs_pkey;
ALTER TABLE build_jobs DROP COLUMN id;
ALTER TABLE build_jobs RENAME COLUMN id_new TO id;
ALTER TABLE build_jobs ADD CONSTRAINT build_jobs_pkey PRIMARY KEY (id);
ALTER TABLE build_jobs RENAME COLUMN created_at TO create_time;

-- ========== blocks ==========
ALTER TABLE blocks ADD COLUMN IF NOT EXISTS id_new bigint GENERATED BY DEFAULT AS IDENTITY;
UPDATE blocks SET id_new = s.rn
  FROM (SELECT id, row_number() OVER (ORDER BY created_at) AS rn FROM blocks) s
  WHERE blocks.id = s.id AND blocks.id_new IS NULL;
ALTER TABLE blocks DROP CONSTRAINT blocks_pkey;
ALTER TABLE blocks DROP COLUMN id;
ALTER TABLE blocks RENAME COLUMN id_new TO id;
ALTER TABLE blocks ADD CONSTRAINT blocks_pkey PRIMARY KEY (id);
ALTER TABLE blocks RENAME COLUMN created_at TO create_time;

-- ========== page_site_slots ==========
ALTER TABLE page_site_slots ADD COLUMN IF NOT EXISTS id_new bigint GENERATED BY DEFAULT AS IDENTITY;
UPDATE page_site_slots SET id_new = s.rn
  FROM (SELECT id, row_number() OVER (ORDER BY created_at) AS rn FROM page_site_slots) s
  WHERE page_site_slots.id = s.id AND page_site_slots.id_new IS NULL;
ALTER TABLE page_site_slots DROP CONSTRAINT page_site_slots_pkey;
ALTER TABLE page_site_slots DROP COLUMN id;
ALTER TABLE page_site_slots RENAME COLUMN id_new TO id;
ALTER TABLE page_site_slots ADD CONSTRAINT page_site_slots_pkey PRIMARY KEY (id);
ALTER TABLE page_site_slots RENAME COLUMN created_at TO create_time;

-- ========== publication_receipts ==========
ALTER TABLE publication_receipts ADD COLUMN IF NOT EXISTS id_new bigint GENERATED BY DEFAULT AS IDENTITY;
UPDATE publication_receipts SET id_new = s.rn
  FROM (SELECT id, row_number() OVER (ORDER BY created_at) AS rn FROM publication_receipts) s
  WHERE publication_receipts.id = s.id AND publication_receipts.id_new IS NULL;
ALTER TABLE publication_receipts DROP CONSTRAINT publication_receipts_pkey;
ALTER TABLE publication_receipts DROP COLUMN id;
ALTER TABLE publication_receipts RENAME COLUMN id_new TO id;
ALTER TABLE publication_receipts ADD CONSTRAINT publication_receipts_pkey PRIMARY KEY (id);
ALTER TABLE publication_receipts RENAME COLUMN created_at TO create_time;

-- ========== inventory_change_reasons（连带 movements.reason_id）==========
ALTER TABLE inventory_change_reasons ADD COLUMN IF NOT EXISTS id_new bigint GENERATED BY DEFAULT AS IDENTITY;
UPDATE inventory_change_reasons SET id_new = s.rn
  FROM (SELECT id, row_number() OVER (ORDER BY created_at) AS rn FROM inventory_change_reasons) s
  WHERE inventory_change_reasons.id = s.id AND inventory_change_reasons.id_new IS NULL;
ALTER TABLE inventory_change_reasons DROP CONSTRAINT inventory_change_reasons_pkey;
ALTER TABLE inventory_change_reasons DROP COLUMN id;
ALTER TABLE inventory_change_reasons RENAME COLUMN id_new TO id;
ALTER TABLE inventory_change_reasons ADD CONSTRAINT inventory_change_reasons_pkey PRIMARY KEY (id);
ALTER TABLE inventory_change_reasons RENAME COLUMN created_at TO create_time;

-- 流水表的 reason_id 是逻辑引用（迁移 134 未建 DB 约束），列类型跟随 reasons.id；
-- 本批数据为空，USING 直接置空即可，历史上已写入的 uuid 引用不存在。
ALTER TABLE inventory_stock_movements ALTER COLUMN reason_id TYPE bigint USING NULL::bigint;
