-- 309 · 商品写路径的静态产物失效 outbox（审计 ARCH-01）。
--
-- 复现的口径差（真实链路）：商品主写路径（Create/Update/Delete + 变体 + 定价 + 分类/品牌/标签）
-- 只调 bumpFragmentCache —— 那只是 Redis 里运行时片段 HTML 的版本号
--（internal/module/runtimefragment/fragment_cache.go），与静态产物字节毫无关系；
-- 而「内容变更 → 依赖扇出 → 静态产物重建」这条链（pipeline.Fanout）此前只有 content 模块
-- 有发射点，商品侧一个都没有。于是改标题 / 改价 / 上下架 / 增删商品之后，
-- 详情页与集合列表页的静态产物可以一直是旧字节，且任何日志都不会提示。
--
-- 为什么是 outbox 而不是「写完直接调 Fanout」：
--   ① 失效必须与商品写入同生共死 —— 事务回滚了就不该有任何事件（直接调用做不到这一点，
--      调用发生在事务之外，回滚后事件已经发出去了）；
--   ② 扇出会触发构建 + 重新发布，不能在 HTTP 请求路径上同步做完；
--   ③ 消费者崩溃 / 进程重启后要能重放（未处理的行还在表里），且重放必须幂等。
--
-- 一行 = 一个依赖键（direct_content:{type}:{id} 或 collection:content:{type}）。
-- 同一实体一次变更会写多行（不同键），它们共享 entity_type / entity_id / entity_revision，
-- 于是「这次变更影响哪些依赖源」在库里是一条可查的事实，而不是内存里的一瞬。

CREATE TABLE IF NOT EXISTS product_outbox_events (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id       uuid NOT NULL,
    entity_type      text NOT NULL,
    entity_id        text NOT NULL,
    entity_revision  bigint NOT NULL,
    dependency_kind  text NOT NULL,
    dependency_key   text NOT NULL,
    create_time      timestamptz NOT NULL DEFAULT now(),
    -- 租约列（与 build_jobs 的 lease 同一手法）：认领时写入，崩溃后无需人工介入，
    -- 到期即可被下一个消费者重新领取 —— 「消费者崩溃可重放」靠的就是它。
    claimed_time     timestamptz NULL,
    processed_time   timestamptz NULL,
    attempts         integer NOT NULL DEFAULT 0,
    last_error       text NOT NULL DEFAULT ''
);

-- 消费者只按「未处理 + id 升序」领取，这条部分索引就是它的工作队列。
CREATE INDEX IF NOT EXISTS idx_product_outbox_pending
    ON product_outbox_events (id) WHERE processed_time IS NULL;

-- 按实体查「这个商品/分类改过几次」（诊断与回归用；entity_revision 由该查询派生）。
CREATE INDEX IF NOT EXISTS idx_product_outbox_entity
    ON product_outbox_events (entity_type, entity_id, id);

ALTER TABLE product_outbox_events DROP CONSTRAINT IF EXISTS product_outbox_events_dependency_kind_check;
ALTER TABLE product_outbox_events ADD CONSTRAINT product_outbox_events_dependency_kind_check
    CHECK (dependency_kind IN ('direct_content', 'content_collection'));

COMMENT ON TABLE product_outbox_events IS '商品写路径的静态产物失效 outbox（审计 ARCH-01）：与商品聚合写入同事务落库，由消费者换算成依赖键后交给 pipeline.Fanout';
COMMENT ON COLUMN product_outbox_events.entity_revision IS '该实体第几次变更（同实体单调递增），用于诊断与去重判断；消费者不依赖严格顺序（失效本身幂等）';
COMMENT ON COLUMN product_outbox_events.dependency_kind IS '依赖源类型：direct_content = 直接引用该实体（详情页），content_collection = 集合成员变化（列表页）';
COMMENT ON COLUMN product_outbox_events.claimed_time IS '最近一次被消费者领取的时刻；超过租约即视为消费者已崩溃，可被重新领取';

-- 本表**不装 RLS 策略**（与 build_jobs 同一情形，见 AGENTS.md 的 DB-009 段）：
-- 它是一张按状态跨工程捞取的队列，消费者要一次领取所有工程的待办；
-- 装 FORCE 策略后未设 app.project_id 的领取会静默 0 行 —— 表现是「商品改了，
-- 依赖事件永远躺在表里没人消费」，日志里什么都没有。工程隔离由写入侧保证
--（行跟随商品聚合所在的工程），读取侧只读「事件 + 依赖键」，不含任何业务字段。
