-- 460 · page_schedules：页面定时上下线（PIPE-7）。
--
-- 背景：此前后台只能「手动发布 / 手动下线」，运营要等到某个时刻上线一个活动页
-- 只能人守着点按钮。本表把「什么时候对该页面的哪个语言做什么」变成一个可持久化、
-- 可认领、可审计的待办。
--
-- 两条到点动作的语义（实现见 internal/module/page/service/page_schedule_apply.go）：
--   · publish —— **只切指针、绝不重新编译**：把 active 目录里该语言的符号链接原子切到
--     排定时冻结的那份暂存产物（page_stagings），再落数据库。理由见
--     internal/module/page/service/page_schedule.go 的文件头（重新编译会把「到点执行」
--     变成一次不可预期的构建，且构建结果与排定时的决策可能不同）。
--   · offline —— 先删符号链接（或落一条 301 产物），再在事务里解除 page_routes 占用 +
--     清该语言的 page_publications 行。顺序与 page_locale_retire.go 同源：
--     指针一旦提交删除就再也没有入口能算出该清哪些链接。
--
-- 键与 page_stagings / page_publications / page_publication_plans 同形（page_id + lang），
-- 四张台账各自回答一个发布问题：暂存了什么、激活了什么、依据哪份语言输入、该在何时做什么。
-- 刻意**不加外键**（与这三张兄弟表一致）：它们是发布流水而不是业务实体，
-- 硬失败会卡住「页面已删、台账待回收」的清理。
--
-- 无 project_id：page_stagings / page_publications / page_publication_plans 同样没有，
-- 四张表同属本模块内部台账、不在迁移 215 的 RLS 清单里 —— 口径一致才不会出现
-- 「同一张表读写在两种作用域下行为不同」。工程作用域由 page_id 经 pages 反查得到。
--
-- 幂等：CREATE TABLE IF NOT EXISTS / 索引 IF NOT EXISTS，重复执行安全。
-- 注册见 register_page_schedule.go（新表，用默认「表存在即跳过」检查）。
--
-- ⚠ 本文件写完后必须用 dbx 跑 `PREPARE chk AS <去掉注释的 SQL>` 做静态校验：
-- mustSQL 只校验 embed 文件**存在**、不校验 SQL 可执行，而迁移链一旦中断会堵住
-- 其后全部注册项（见 AGENTS.md §数据库·迁移）。

CREATE TABLE IF NOT EXISTS page_schedules (
    id                 bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    page_id            uuid        NOT NULL,
    lang               text        NOT NULL,
    action             text        NOT NULL CHECK (action IN ('publish', 'offline')),
    scheduled_at       timestamptz NOT NULL,
    status             text        NOT NULL DEFAULT 'pending'
                       CHECK (status IN ('pending', 'running', 'done', 'failed', 'canceled')),
    -- 排定时冻结的产物行 id（publish 用；offline 为空）。
    -- 记行 id 而不是 hash：产物行是「这次排定依据的产物」的持久身份，
    -- hash 由它反查（page_artifacts.artifact_hash），回执与恢复也按 id 表达。
    artifact_id        uuid        NULL,
    -- 排定当时 pages.draft_version 的取值（publish 的前置判据）。
    -- 到点时与 pages.draft_version 比对：不等即「排定后草稿被改过」——
    -- 那意味着这次要上线的产物不再代表当前草稿，硬失败而不是拿现在的内容顶上。
    draft_version      bigint      NOT NULL DEFAULT 0,
    -- 下线时旧路径的落点（空 = 直接下线，访问面 404）。非空时落一条 301 产物；
    -- 路径是站点内的绝对路径（与 page_routes.path 同口径，无语言前缀之外的差异）。
    redirect_path      text        NULL,
    -- 认领租约：claim 时由数据库原子产生（gen_random_uuid），完成/失败写入必须带同一个
    -- 令牌 —— 租约过期被回收并重新认领后，旧 worker 的结果不能再落库（完成归属，
    -- 与 build_jobs 的 lease_token 同源，见 internal/module/build/model/build_model.go）。
    lease_token        uuid        NULL,
    lease_expires_time timestamptz NULL,
    -- 认领次数：排障时「这条到底试过几次」的唯一证据（同 build_jobs.attempt）。
    attempts           int         NOT NULL DEFAULT 0,
    -- 最近一次失败的**业务 key**（page enums 常量，如 ErrRebuildRequired）或归口 key。
    -- 刻意不存原文：这一列会显示在后台，存原始错误等于把 PostgreSQL 原文摆到页面上
    -- （门禁 check-no-internal-error-leak.sh 的同一条判据）；原文只进日志。
    last_error         text        NULL,
    -- 发起人 = sys_admin.id（bigint）。全库 create_by 都是 bigint（030 起的既有口径），
    -- 这里跟随；可空 = 系统排定（无发起人）。
    create_by          bigint      NULL,
    create_time        timestamptz NOT NULL DEFAULT now(),
    update_time        timestamptz NOT NULL DEFAULT now()
);

-- 到点扫描的驱动索引：`status = 'pending' AND scheduled_at <= now()`（分批 claim）。
CREATE INDEX IF NOT EXISTS idx_page_schedules_due ON page_schedules (status, scheduled_at);

-- 租约回收的驱动索引（只覆盖 running 行，与 build_jobs 的 idx_build_jobs_lease_expires 同形）。
CREATE INDEX IF NOT EXISTS idx_page_schedules_lease ON page_schedules (lease_expires_time)
    WHERE status = 'running';

-- 同一 (page, lang, action) 同一时刻只能有一条待执行 / 执行中的排定。
-- 为什么含 running：pending 被认领后仍占着这个动作，此时再排一条会让两轮执行
-- 同时操作同一路径（同 build_jobs 的 uq_build_jobs_running_source 的理由）。
-- 终态（done / failed / canceled）不占键，因此「上一次失败的排定不挡住重新排定」。
CREATE UNIQUE INDEX IF NOT EXISTS uq_page_schedules_active
    ON page_schedules (page_id, lang, action) WHERE status IN ('pending', 'running');

COMMENT ON TABLE page_schedules IS '页面定时上下线待办（PIPE-7）：键 (page_id, lang)，action=publish 到点只切指针不重编译，offline 先删链接再清占用与发布指针';
COMMENT ON COLUMN page_schedules.action IS 'publish=到点上线（切符号链接到冻结的暂存产物）；offline=到点下线（删链接，redirect_path 非空时落 301）';
COMMENT ON COLUMN page_schedules.scheduled_at IS '到点时刻（绝对时刻，timestamptz）；后台按站点时区解释输入输出（pkg/sitetz）';
COMMENT ON COLUMN page_schedules.status IS 'pending=待执行，running=已认领（持租约），done/failed/canceled=终态';
COMMENT ON COLUMN page_schedules.artifact_id IS '排定时冻结的产物行 id（page_artifacts.id）；publish 到点激活它的 hash，不复构建';
COMMENT ON COLUMN page_schedules.draft_version IS '排定当时的 pages.draft_version；到点不等即判「草稿已变更」并置 failed（口径与 publish() 的 ErrRebuildRequired 同源）';
COMMENT ON COLUMN page_schedules.redirect_path IS '下线时的 301 落点（空 = 直接下线 404）；与 page_routes.path 同口径的站点内绝对路径';
COMMENT ON COLUMN page_schedules.lease_token IS '认领令牌：完成/失败写入必须带上它，租约过期被重新认领后旧 worker 的结果被丢弃';
COMMENT ON COLUMN page_schedules.lease_expires_time IS '租约到期时刻；超时未结案的行由 ReclaimExpiredSchedules 回收（attempts 达上限则置 failed）';
COMMENT ON COLUMN page_schedules.attempts IS '被认领次数（排障证据：这条排定试过几次）';
COMMENT ON COLUMN page_schedules.last_error IS '最近一次失败的业务 key（page enums 常量）或归口 key；原文只进日志，不落库';
COMMENT ON COLUMN page_schedules.create_by IS '排定发起人 = sys_admin.id（bigint，与全库 create_by 同型）；可空 = 系统排定';
