-- 488 · sys_dict 初始数据 seed：语言（language）+ 货币（currency）。
--
-- 目标表见 486_sys_dict.sql（本文件只灌数据，不改结构）。共 278 行：
--   · 语言 100 行（type='language'）：常用「语言-地区」标签清单，code 用完整语言码
--   · 货币 178 行（type='currency'）：ISO 4217 全量现行码
--
-- 数据来源与抓取日期（2026-10-02，全部实际抓取后由脚本解析生成，无一处凭记忆写）：
--   · 货币码 / 数字码 / 小数位 —— datasets/currency-codes 的 data/codes-all.csv
--     （ISO 4217 官方表，含 WithdrawalDate；本批只取 WithdrawalDate 为空且在用的码，
--      按 AlphabeticCode 去重后 178 个）。货币符号取自 dr5hn/
--     countries-states-cities-database 的 json/countries.json（currency_symbol）。
--   · 语言 ISO 639-1 / ISO 639-2(B) —— datasets/language-codes 的 data/language-codes.csv
--     与 data/language-codes-3b2.csv（**639-2/B 书目码**：chi / ger / fre / cze / wel …，
--     不是术语码 zho / deu / fra）。
--   · 语言-地区清单本身是**项目定稿的常用清单**（不是 BCP 47 全量）：覆盖各主要语言与常见
--     地区变体；语言子标签取 ISO 639-1，地区子标签取 ISO 3166-1 alpha-2。
--
-- 署名：Data by Countries States Cities Database (https://github.com/dr5hn/countries-states-cities-database),
--       ODbL v1.0 —— 开源数据库许可，要求署名（本文件即署名位置）。
--       Currency codes by datasets/currency-codes (ISO 4217); language codes by datasets/language-codes (ISO 639)。
--
-- 口径决策（**知情选择，不是数据错误**，改口径前先读 486 的列注释）：
--   1. code 用**完整语言码** zh-CN / en-US（而不是 zh / en），与 sys_i18n.lang /
--      sys_translation.lang / project_locales.lang / 产物 Manifest.lang 同口径（见 486 注释）。
--   2. url_code 的取值规则：同一主语言在本清单里只有一个条目时取语言子标签（ja / ru / hi …）；
--      有多个地区变体时，清单中排第一的那个取语言子标签、其余取完整语言码
--      （zh-CN→zh、zh-TW→zh-tw、en-US→en、en-GB→en-gb、de-DE→de、de-AT→de-at …）。
--      **一律小写**：URL 路径段惯例如此，也与项目内置短码映射（zh / en）同形，大写会对不上。
--      注意只有这一列小写 —— code 列仍是 BCP 47 的大小写形式（zh-TW / en-GB 不变）。
--      这是「显式覆盖值」，未收录语言的确定性回退仍在代码里（486 注释）。
--   3. ui_available 只有 zh-CN 与 en-US 为 true —— 依据是 seed 执行时本机 sys_i18n 实际只有这两个
--      lang，其余语言尚无后台界面译文。**本列是 seed 时按 sys_i18n 实际语种填充的快照，不是派生列、
--      不会自动跟随 sys_i18n 变化**：将来给 sys_i18n 增加界面语种时，必须同步更新本列（或同步更新
--      本 seed），否则后台语言下拉会缺选项。
--   4. minor_unit 取 ISO 4217。其中 13 个码（XAU/XAG/XPT/XPD 贵金属、XDR/XSU/XUA/Bond Markets
--      XBA-XBD 记账单位、XTS 测试码、XXX 无货币）在 ISO 4217 里标注 N.A.（没有小数位）；
--      本列 NOT NULL（CK 约束），按 N.A. → 0 落库。它们不参与普通金额计算，需要时以本注释为准。
--      其余 165 个码的 minor_unit 是 ISO 4217 原值（JPY=0 / CNY=2 / KWD=3 …），逐条来自数据源。
--   5. symbol 为 NULL 的 26 行有两类：ISO 4217 的记账单位 / 贵金属 / 测试码（无通用符号），
--      以及 BOV/CHE/CHW/CLF/COU/MXV/SVC/USN/UYI/UYW/VED 等只用于特定记账场景的地方性单位 ——
--      它们没有单一通用符号，硬填会误导，故留空（列可空）。常见货币符号来自 dr5hn，全部有值。
--
-- 幂等：单条 INSERT … VALUES … ON CONFLICT (type, code) DO NOTHING。
--   · 必须**单语句**：seed 由 migrator.applySeed 用一次 db.Exec 整段执行（不做语句拆分）。
--   · 手工调整过的行不会被覆盖（DO NOTHING），重复执行安全。
--
-- 门槛判据在 register_sys_reference.go 里按 type 分别精确计数（上界封闭）。

INSERT INTO sys_dict (type, code, url_code, iso639_1, iso639_2, ui_available,
                      symbol, minor_unit, numeric_code, sort_order)
VALUES
  ('language', 'zh-CN', 'zh', 'zh', 'chi', true, NULL, NULL, NULL, 0),
  ('language', 'zh-TW', 'zh-tw', 'zh', 'chi', false, NULL, NULL, NULL, 1),
  ('language', 'zh-HK', 'zh-hk', 'zh', 'chi', false, NULL, NULL, NULL, 2),
  ('language', 'zh-SG', 'zh-sg', 'zh', 'chi', false, NULL, NULL, NULL, 3),
  ('language', 'en-US', 'en', 'en', 'eng', true, NULL, NULL, NULL, 4),
  ('language', 'en-GB', 'en-gb', 'en', 'eng', false, NULL, NULL, NULL, 5),
  ('language', 'en-AU', 'en-au', 'en', 'eng', false, NULL, NULL, NULL, 6),
  ('language', 'en-CA', 'en-ca', 'en', 'eng', false, NULL, NULL, NULL, 7),
  ('language', 'en-NZ', 'en-nz', 'en', 'eng', false, NULL, NULL, NULL, 8),
  ('language', 'en-IE', 'en-ie', 'en', 'eng', false, NULL, NULL, NULL, 9),
  ('language', 'en-IN', 'en-in', 'en', 'eng', false, NULL, NULL, NULL, 10),
  ('language', 'en-SG', 'en-sg', 'en', 'eng', false, NULL, NULL, NULL, 11),
  ('language', 'en-ZA', 'en-za', 'en', 'eng', false, NULL, NULL, NULL, 12),
  ('language', 'en-PH', 'en-ph', 'en', 'eng', false, NULL, NULL, NULL, 13),
  ('language', 'en-MY', 'en-my', 'en', 'eng', false, NULL, NULL, NULL, 14),
  ('language', 'ja-JP', 'ja', 'ja', 'jpn', false, NULL, NULL, NULL, 15),
  ('language', 'ko-KR', 'ko', 'ko', 'kor', false, NULL, NULL, NULL, 16),
  ('language', 'de-DE', 'de', 'de', 'ger', false, NULL, NULL, NULL, 17),
  ('language', 'de-AT', 'de-at', 'de', 'ger', false, NULL, NULL, NULL, 18),
  ('language', 'de-CH', 'de-ch', 'de', 'ger', false, NULL, NULL, NULL, 19),
  ('language', 'fr-FR', 'fr', 'fr', 'fre', false, NULL, NULL, NULL, 20),
  ('language', 'fr-CA', 'fr-ca', 'fr', 'fre', false, NULL, NULL, NULL, 21),
  ('language', 'fr-BE', 'fr-be', 'fr', 'fre', false, NULL, NULL, NULL, 22),
  ('language', 'fr-CH', 'fr-ch', 'fr', 'fre', false, NULL, NULL, NULL, 23),
  ('language', 'es-ES', 'es', 'es', 'spa', false, NULL, NULL, NULL, 24),
  ('language', 'es-MX', 'es-mx', 'es', 'spa', false, NULL, NULL, NULL, 25),
  ('language', 'es-AR', 'es-ar', 'es', 'spa', false, NULL, NULL, NULL, 26),
  ('language', 'es-CL', 'es-cl', 'es', 'spa', false, NULL, NULL, NULL, 27),
  ('language', 'es-CO', 'es-co', 'es', 'spa', false, NULL, NULL, NULL, 28),
  ('language', 'es-PE', 'es-pe', 'es', 'spa', false, NULL, NULL, NULL, 29),
  ('language', 'pt-BR', 'pt', 'pt', 'por', false, NULL, NULL, NULL, 30),
  ('language', 'pt-PT', 'pt-pt', 'pt', 'por', false, NULL, NULL, NULL, 31),
  ('language', 'it-IT', 'it', 'it', 'ita', false, NULL, NULL, NULL, 32),
  ('language', 'it-CH', 'it-ch', 'it', 'ita', false, NULL, NULL, NULL, 33),
  ('language', 'nl-NL', 'nl', 'nl', 'dut', false, NULL, NULL, NULL, 34),
  ('language', 'nl-BE', 'nl-be', 'nl', 'dut', false, NULL, NULL, NULL, 35),
  ('language', 'ru-RU', 'ru', 'ru', 'rus', false, NULL, NULL, NULL, 36),
  ('language', 'uk-UA', 'uk', 'uk', 'ukr', false, NULL, NULL, NULL, 37),
  ('language', 'be-BY', 'be', 'be', 'bel', false, NULL, NULL, NULL, 38),
  ('language', 'pl-PL', 'pl', 'pl', 'pol', false, NULL, NULL, NULL, 39),
  ('language', 'cs-CZ', 'cs', 'cs', 'cze', false, NULL, NULL, NULL, 40),
  ('language', 'sk-SK', 'sk', 'sk', 'slo', false, NULL, NULL, NULL, 41),
  ('language', 'hu-HU', 'hu', 'hu', 'hun', false, NULL, NULL, NULL, 42),
  ('language', 'ro-RO', 'ro', 'ro', 'rum', false, NULL, NULL, NULL, 43),
  ('language', 'bg-BG', 'bg', 'bg', 'bul', false, NULL, NULL, NULL, 44),
  ('language', 'el-GR', 'el', 'el', 'gre', false, NULL, NULL, NULL, 45),
  ('language', 'hr-HR', 'hr', 'hr', 'hrv', false, NULL, NULL, NULL, 46),
  ('language', 'sr-RS', 'sr', 'sr', 'srp', false, NULL, NULL, NULL, 47),
  ('language', 'sl-SI', 'sl', 'sl', 'slv', false, NULL, NULL, NULL, 48),
  ('language', 'sq-AL', 'sq', 'sq', 'alb', false, NULL, NULL, NULL, 49),
  ('language', 'mk-MK', 'mk', 'mk', 'mac', false, NULL, NULL, NULL, 50),
  ('language', 'sv-SE', 'sv', 'sv', 'swe', false, NULL, NULL, NULL, 51),
  ('language', 'no-NO', 'no', 'no', 'nor', false, NULL, NULL, NULL, 52),
  ('language', 'da-DK', 'da', 'da', 'dan', false, NULL, NULL, NULL, 53),
  ('language', 'fi-FI', 'fi', 'fi', 'fin', false, NULL, NULL, NULL, 54),
  ('language', 'is-IS', 'is', 'is', 'ice', false, NULL, NULL, NULL, 55),
  ('language', 'et-EE', 'et', 'et', 'est', false, NULL, NULL, NULL, 56),
  ('language', 'lv-LV', 'lv', 'lv', 'lav', false, NULL, NULL, NULL, 57),
  ('language', 'lt-LT', 'lt', 'lt', 'lit', false, NULL, NULL, NULL, 58),
  ('language', 'tr-TR', 'tr', 'tr', 'tur', false, NULL, NULL, NULL, 59),
  ('language', 'az-AZ', 'az', 'az', 'aze', false, NULL, NULL, NULL, 60),
  ('language', 'kk-KZ', 'kk', 'kk', 'kaz', false, NULL, NULL, NULL, 61),
  ('language', 'uz-UZ', 'uz', 'uz', 'uzb', false, NULL, NULL, NULL, 62),
  ('language', 'ka-GE', 'ka', 'ka', 'geo', false, NULL, NULL, NULL, 63),
  ('language', 'hy-AM', 'hy', 'hy', 'arm', false, NULL, NULL, NULL, 64),
  ('language', 'ar-SA', 'ar', 'ar', 'ara', false, NULL, NULL, NULL, 65),
  ('language', 'ar-AE', 'ar-ae', 'ar', 'ara', false, NULL, NULL, NULL, 66),
  ('language', 'ar-EG', 'ar-eg', 'ar', 'ara', false, NULL, NULL, NULL, 67),
  ('language', 'ar-MA', 'ar-ma', 'ar', 'ara', false, NULL, NULL, NULL, 68),
  ('language', 'he-IL', 'he', 'he', 'heb', false, NULL, NULL, NULL, 69),
  ('language', 'fa-IR', 'fa', 'fa', 'per', false, NULL, NULL, NULL, 70),
  ('language', 'ur-PK', 'ur', 'ur', 'urd', false, NULL, NULL, NULL, 71),
  ('language', 'hi-IN', 'hi', 'hi', 'hin', false, NULL, NULL, NULL, 72),
  ('language', 'bn-IN', 'bn', 'bn', 'ben', false, NULL, NULL, NULL, 73),
  ('language', 'ta-IN', 'ta', 'ta', 'tam', false, NULL, NULL, NULL, 74),
  ('language', 'te-IN', 'te', 'te', 'tel', false, NULL, NULL, NULL, 75),
  ('language', 'mr-IN', 'mr', 'mr', 'mar', false, NULL, NULL, NULL, 76),
  ('language', 'gu-IN', 'gu', 'gu', 'guj', false, NULL, NULL, NULL, 77),
  ('language', 'ml-IN', 'ml', 'ml', 'mal', false, NULL, NULL, NULL, 78),
  ('language', 'ne-NP', 'ne', 'ne', 'nep', false, NULL, NULL, NULL, 79),
  ('language', 'si-LK', 'si', 'si', 'sin', false, NULL, NULL, NULL, 80),
  ('language', 'th-TH', 'th', 'th', 'tha', false, NULL, NULL, NULL, 81),
  ('language', 'vi-VN', 'vi', 'vi', 'vie', false, NULL, NULL, NULL, 82),
  ('language', 'id-ID', 'id', 'id', 'ind', false, NULL, NULL, NULL, 83),
  ('language', 'ms-MY', 'ms', 'ms', 'may', false, NULL, NULL, NULL, 84),
  ('language', 'fil-PH', 'fil', NULL, NULL, false, NULL, NULL, NULL, 85),
  ('language', 'km-KH', 'km', 'km', 'khm', false, NULL, NULL, NULL, 86),
  ('language', 'lo-LA', 'lo', 'lo', 'lao', false, NULL, NULL, NULL, 87),
  ('language', 'my-MM', 'my', 'my', 'bur', false, NULL, NULL, NULL, 88),
  ('language', 'mn-MN', 'mn', 'mn', 'mon', false, NULL, NULL, NULL, 89),
  ('language', 'sw-KE', 'sw', 'sw', 'swa', false, NULL, NULL, NULL, 90),
  ('language', 'am-ET', 'am', 'am', 'amh', false, NULL, NULL, NULL, 91),
  ('language', 'ha-NG', 'ha', 'ha', 'hau', false, NULL, NULL, NULL, 92),
  ('language', 'zu-ZA', 'zu', 'zu', 'zul', false, NULL, NULL, NULL, 93),
  ('language', 'af-ZA', 'af', 'af', 'afr', false, NULL, NULL, NULL, 94),
  ('language', 'ca-ES', 'ca', 'ca', 'cat', false, NULL, NULL, NULL, 95),
  ('language', 'eu-ES', 'eu', 'eu', 'baq', false, NULL, NULL, NULL, 96),
  ('language', 'gl-ES', 'gl', 'gl', 'glg', false, NULL, NULL, NULL, 97),
  ('language', 'cy-GB', 'cy', 'cy', 'wel', false, NULL, NULL, NULL, 98),
  ('language', 'ga-IE', 'ga', 'ga', 'gle', false, NULL, NULL, NULL, 99),
  ('currency', 'AED', NULL, NULL, NULL, false, 'إ.د', 2, '784', 0),
  ('currency', 'AFN', NULL, NULL, NULL, false, '؋', 2, '971', 1),
  ('currency', 'ALL', NULL, NULL, NULL, false, 'Lek', 2, '008', 2),
  ('currency', 'AMD', NULL, NULL, NULL, false, '֏', 2, '051', 3),
  ('currency', 'AOA', NULL, NULL, NULL, false, 'Kz', 2, '973', 4),
  ('currency', 'ARS', NULL, NULL, NULL, false, '$', 2, '032', 5),
  ('currency', 'AUD', NULL, NULL, NULL, false, '$', 2, '036', 6),
  ('currency', 'AWG', NULL, NULL, NULL, false, 'ƒ', 2, '533', 7),
  ('currency', 'AZN', NULL, NULL, NULL, false, 'm', 2, '944', 8),
  ('currency', 'BAM', NULL, NULL, NULL, false, 'KM', 2, '977', 9),
  ('currency', 'BBD', NULL, NULL, NULL, false, 'Bds$', 2, '052', 10),
  ('currency', 'BDT', NULL, NULL, NULL, false, '৳', 2, '050', 11),
  ('currency', 'BHD', NULL, NULL, NULL, false, '.د.ب', 3, '048', 12),
  ('currency', 'BIF', NULL, NULL, NULL, false, 'FBu', 0, '108', 13),
  ('currency', 'BMD', NULL, NULL, NULL, false, '$', 2, '060', 14),
  ('currency', 'BND', NULL, NULL, NULL, false, 'B$', 2, '096', 15),
  ('currency', 'BOB', NULL, NULL, NULL, false, 'Bs.', 2, '068', 16),
  ('currency', 'BOV', NULL, NULL, NULL, false, NULL, 2, '984', 17),
  ('currency', 'BRL', NULL, NULL, NULL, false, 'R$', 2, '986', 18),
  ('currency', 'BSD', NULL, NULL, NULL, false, 'B$', 2, '044', 19),
  ('currency', 'BTN', NULL, NULL, NULL, false, 'Nu.', 2, '064', 20),
  ('currency', 'BWP', NULL, NULL, NULL, false, 'P', 2, '072', 21),
  ('currency', 'BYN', NULL, NULL, NULL, false, 'Br', 2, '933', 22),
  ('currency', 'BZD', NULL, NULL, NULL, false, '$', 2, '084', 23),
  ('currency', 'CAD', NULL, NULL, NULL, false, '$', 2, '124', 24),
  ('currency', 'CDF', NULL, NULL, NULL, false, 'FC', 2, '976', 25),
  ('currency', 'CHE', NULL, NULL, NULL, false, NULL, 2, '947', 26),
  ('currency', 'CHF', NULL, NULL, NULL, false, 'CHf', 2, '756', 27),
  ('currency', 'CHW', NULL, NULL, NULL, false, NULL, 2, '948', 28),
  ('currency', 'CLF', NULL, NULL, NULL, false, NULL, 4, '990', 29),
  ('currency', 'CLP', NULL, NULL, NULL, false, '$', 0, '152', 30),
  ('currency', 'CNY', NULL, NULL, NULL, false, '¥', 2, '156', 31),
  ('currency', 'COP', NULL, NULL, NULL, false, '$', 2, '170', 32),
  ('currency', 'COU', NULL, NULL, NULL, false, NULL, 2, '970', 33),
  ('currency', 'CRC', NULL, NULL, NULL, false, '₡', 2, '188', 34),
  ('currency', 'CUP', NULL, NULL, NULL, false, '$', 2, '192', 35),
  ('currency', 'CVE', NULL, NULL, NULL, false, '$', 2, '132', 36),
  ('currency', 'CZK', NULL, NULL, NULL, false, 'Kč', 2, '203', 37),
  ('currency', 'DJF', NULL, NULL, NULL, false, 'Fdj', 0, '262', 38),
  ('currency', 'DKK', NULL, NULL, NULL, false, 'Kr.', 2, '208', 39),
  ('currency', 'DOP', NULL, NULL, NULL, false, '$', 2, '214', 40),
  ('currency', 'DZD', NULL, NULL, NULL, false, 'دج', 2, '012', 41),
  ('currency', 'EGP', NULL, NULL, NULL, false, 'ج.م', 2, '818', 42),
  ('currency', 'ERN', NULL, NULL, NULL, false, 'Nfk', 2, '232', 43),
  ('currency', 'ETB', NULL, NULL, NULL, false, 'Nkf', 2, '230', 44),
  ('currency', 'EUR', NULL, NULL, NULL, false, '€', 2, '978', 45),
  ('currency', 'FJD', NULL, NULL, NULL, false, 'FJ$', 2, '242', 46),
  ('currency', 'FKP', NULL, NULL, NULL, false, '£', 2, '238', 47),
  ('currency', 'GBP', NULL, NULL, NULL, false, '£', 2, '826', 48),
  ('currency', 'GEL', NULL, NULL, NULL, false, 'ლ', 2, '981', 49),
  ('currency', 'GHS', NULL, NULL, NULL, false, 'GH₵', 2, '936', 50),
  ('currency', 'GIP', NULL, NULL, NULL, false, '£', 2, '292', 51),
  ('currency', 'GMD', NULL, NULL, NULL, false, 'D', 2, '270', 52),
  ('currency', 'GNF', NULL, NULL, NULL, false, 'FG', 0, '324', 53),
  ('currency', 'GTQ', NULL, NULL, NULL, false, 'Q', 2, '320', 54),
  ('currency', 'GYD', NULL, NULL, NULL, false, '$', 2, '328', 55),
  ('currency', 'HKD', NULL, NULL, NULL, false, '$', 2, '344', 56),
  ('currency', 'HNL', NULL, NULL, NULL, false, 'L', 2, '340', 57),
  ('currency', 'HTG', NULL, NULL, NULL, false, 'G', 2, '332', 58),
  ('currency', 'HUF', NULL, NULL, NULL, false, 'Ft', 2, '348', 59),
  ('currency', 'IDR', NULL, NULL, NULL, false, 'Rp', 2, '360', 60),
  ('currency', 'ILS', NULL, NULL, NULL, false, '₪', 2, '376', 61),
  ('currency', 'INR', NULL, NULL, NULL, false, '₹', 2, '356', 62),
  ('currency', 'IQD', NULL, NULL, NULL, false, 'د.ع', 3, '368', 63),
  ('currency', 'IRR', NULL, NULL, NULL, false, '﷼', 2, '364', 64),
  ('currency', 'ISK', NULL, NULL, NULL, false, 'ko', 0, '352', 65),
  ('currency', 'JMD', NULL, NULL, NULL, false, 'J$', 2, '388', 66),
  ('currency', 'JOD', NULL, NULL, NULL, false, 'ا.د', 3, '400', 67),
  ('currency', 'JPY', NULL, NULL, NULL, false, '¥', 0, '392', 68),
  ('currency', 'KES', NULL, NULL, NULL, false, 'KSh', 2, '404', 69),
  ('currency', 'KGS', NULL, NULL, NULL, false, 'лв', 2, '417', 70),
  ('currency', 'KHR', NULL, NULL, NULL, false, 'KHR', 2, '116', 71),
  ('currency', 'KMF', NULL, NULL, NULL, false, 'CF', 0, '174', 72),
  ('currency', 'KPW', NULL, NULL, NULL, false, '₩', 2, '408', 73),
  ('currency', 'KRW', NULL, NULL, NULL, false, '₩', 0, '410', 74),
  ('currency', 'KWD', NULL, NULL, NULL, false, 'ك.د', 3, '414', 75),
  ('currency', 'KYD', NULL, NULL, NULL, false, '$', 2, '136', 76),
  ('currency', 'KZT', NULL, NULL, NULL, false, 'лв', 2, '398', 77),
  ('currency', 'LAK', NULL, NULL, NULL, false, '₭', 2, '418', 78),
  ('currency', 'LBP', NULL, NULL, NULL, false, '£', 2, '422', 79),
  ('currency', 'LKR', NULL, NULL, NULL, false, 'Rs', 2, '144', 80),
  ('currency', 'LRD', NULL, NULL, NULL, false, '$', 2, '430', 81),
  ('currency', 'LSL', NULL, NULL, NULL, false, 'L', 2, '426', 82),
  ('currency', 'LYD', NULL, NULL, NULL, false, 'د.ل', 3, '434', 83),
  ('currency', 'MAD', NULL, NULL, NULL, false, 'DH', 2, '504', 84),
  ('currency', 'MDL', NULL, NULL, NULL, false, 'L', 2, '498', 85),
  ('currency', 'MGA', NULL, NULL, NULL, false, 'Ar', 2, '969', 86),
  ('currency', 'MKD', NULL, NULL, NULL, false, 'ден', 2, '807', 87),
  ('currency', 'MMK', NULL, NULL, NULL, false, 'K', 2, '104', 88),
  ('currency', 'MNT', NULL, NULL, NULL, false, '₮', 2, '496', 89),
  ('currency', 'MOP', NULL, NULL, NULL, false, '$', 2, '446', 90),
  ('currency', 'MRU', NULL, NULL, NULL, false, 'UM', 2, '929', 91),
  ('currency', 'MUR', NULL, NULL, NULL, false, '₨', 2, '480', 92),
  ('currency', 'MVR', NULL, NULL, NULL, false, 'Rf', 2, '462', 93),
  ('currency', 'MWK', NULL, NULL, NULL, false, 'MK', 2, '454', 94),
  ('currency', 'MXN', NULL, NULL, NULL, false, '$', 2, '484', 95),
  ('currency', 'MXV', NULL, NULL, NULL, false, NULL, 2, '979', 96),
  ('currency', 'MYR', NULL, NULL, NULL, false, 'RM', 2, '458', 97),
  ('currency', 'MZN', NULL, NULL, NULL, false, 'MT', 2, '943', 98),
  ('currency', 'NAD', NULL, NULL, NULL, false, '$', 2, '516', 99),
  ('currency', 'NGN', NULL, NULL, NULL, false, '₦', 2, '566', 100),
  ('currency', 'NIO', NULL, NULL, NULL, false, 'C$', 2, '558', 101),
  ('currency', 'NOK', NULL, NULL, NULL, false, 'ko', 2, '578', 102),
  ('currency', 'NPR', NULL, NULL, NULL, false, '₨', 2, '524', 103),
  ('currency', 'NZD', NULL, NULL, NULL, false, '$', 2, '554', 104),
  ('currency', 'OMR', NULL, NULL, NULL, false, '.ع.ر', 3, '512', 105),
  ('currency', 'PAB', NULL, NULL, NULL, false, 'B/.', 2, '590', 106),
  ('currency', 'PEN', NULL, NULL, NULL, false, 'S/.', 2, '604', 107),
  ('currency', 'PGK', NULL, NULL, NULL, false, 'K', 2, '598', 108),
  ('currency', 'PHP', NULL, NULL, NULL, false, '₱', 2, '608', 109),
  ('currency', 'PKR', NULL, NULL, NULL, false, '₨', 2, '586', 110),
  ('currency', 'PLN', NULL, NULL, NULL, false, 'zł', 2, '985', 111),
  ('currency', 'PYG', NULL, NULL, NULL, false, '₲', 0, '600', 112),
  ('currency', 'QAR', NULL, NULL, NULL, false, 'ق.ر', 2, '634', 113),
  ('currency', 'RON', NULL, NULL, NULL, false, 'lei', 2, '946', 114),
  ('currency', 'RSD', NULL, NULL, NULL, false, 'din', 2, '941', 115),
  ('currency', 'RUB', NULL, NULL, NULL, false, '₽', 2, '643', 116),
  ('currency', 'RWF', NULL, NULL, NULL, false, 'FRw', 0, '646', 117),
  ('currency', 'SAR', NULL, NULL, NULL, false, '﷼', 2, '682', 118),
  ('currency', 'SBD', NULL, NULL, NULL, false, 'Si$', 2, '090', 119),
  ('currency', 'SCR', NULL, NULL, NULL, false, 'SRe', 2, '690', 120),
  ('currency', 'SDG', NULL, NULL, NULL, false, '.س.ج', 2, '938', 121),
  ('currency', 'SEK', NULL, NULL, NULL, false, 'ko', 2, '752', 122),
  ('currency', 'SGD', NULL, NULL, NULL, false, '$', 2, '702', 123),
  ('currency', 'SHP', NULL, NULL, NULL, false, '£', 2, '654', 124),
  ('currency', 'SLE', NULL, NULL, NULL, false, 'Le', 2, '925', 125),
  ('currency', 'SOS', NULL, NULL, NULL, false, 'Sh.so.', 2, '706', 126),
  ('currency', 'SRD', NULL, NULL, NULL, false, '$', 2, '968', 127),
  ('currency', 'SSP', NULL, NULL, NULL, false, '£', 2, '728', 128),
  ('currency', 'STN', NULL, NULL, NULL, false, 'Db', 2, '930', 129),
  ('currency', 'SVC', NULL, NULL, NULL, false, NULL, 2, '222', 130),
  ('currency', 'SYP', NULL, NULL, NULL, false, 'LS', 2, '760', 131),
  ('currency', 'SZL', NULL, NULL, NULL, false, 'E', 2, '748', 132),
  ('currency', 'THB', NULL, NULL, NULL, false, '฿', 2, '764', 133),
  ('currency', 'TJS', NULL, NULL, NULL, false, 'SM', 2, '972', 134),
  ('currency', 'TMT', NULL, NULL, NULL, false, 'T', 2, '934', 135),
  ('currency', 'TND', NULL, NULL, NULL, false, 'ت.د', 3, '788', 136),
  ('currency', 'TOP', NULL, NULL, NULL, false, '$', 2, '776', 137),
  ('currency', 'TRY', NULL, NULL, NULL, false, '₺', 2, '949', 138),
  ('currency', 'TTD', NULL, NULL, NULL, false, '$', 2, '780', 139),
  ('currency', 'TWD', NULL, NULL, NULL, false, '$', 2, '901', 140),
  ('currency', 'TZS', NULL, NULL, NULL, false, 'TSh', 2, '834', 141),
  ('currency', 'UAH', NULL, NULL, NULL, false, '₴', 2, '980', 142),
  ('currency', 'UGX', NULL, NULL, NULL, false, 'USh', 0, '800', 143),
  ('currency', 'USD', NULL, NULL, NULL, false, '$', 2, '840', 144),
  ('currency', 'USN', NULL, NULL, NULL, false, NULL, 2, '997', 145),
  ('currency', 'UYI', NULL, NULL, NULL, false, NULL, 0, '940', 146),
  ('currency', 'UYU', NULL, NULL, NULL, false, '$', 2, '858', 147),
  ('currency', 'UYW', NULL, NULL, NULL, false, NULL, 4, '927', 148),
  ('currency', 'UZS', NULL, NULL, NULL, false, 'лв', 2, '860', 149),
  ('currency', 'VED', NULL, NULL, NULL, false, NULL, 2, '926', 150),
  ('currency', 'VES', NULL, NULL, NULL, false, 'Bs', 2, '928', 151),
  ('currency', 'VND', NULL, NULL, NULL, false, '₫', 0, '704', 152),
  ('currency', 'VUV', NULL, NULL, NULL, false, 'VT', 0, '548', 153),
  ('currency', 'WST', NULL, NULL, NULL, false, 'SAT', 2, '882', 154),
  ('currency', 'XAD', NULL, NULL, NULL, false, NULL, 2, '396', 155),
  ('currency', 'XAF', NULL, NULL, NULL, false, 'FCFA', 0, '950', 156),
  ('currency', 'XAG', NULL, NULL, NULL, false, NULL, 0, '961', 157),
  ('currency', 'XAU', NULL, NULL, NULL, false, NULL, 0, '959', 158),
  ('currency', 'XBA', NULL, NULL, NULL, false, NULL, 0, '955', 159),
  ('currency', 'XBB', NULL, NULL, NULL, false, NULL, 0, '956', 160),
  ('currency', 'XBC', NULL, NULL, NULL, false, NULL, 0, '957', 161),
  ('currency', 'XBD', NULL, NULL, NULL, false, NULL, 0, '958', 162),
  ('currency', 'XCD', NULL, NULL, NULL, false, '$', 2, '951', 163),
  ('currency', 'XCG', NULL, NULL, NULL, false, NULL, 2, '532', 164),
  ('currency', 'XDR', NULL, NULL, NULL, false, NULL, 0, '960', 165),
  ('currency', 'XOF', NULL, NULL, NULL, false, 'CFA', 0, '952', 166),
  ('currency', 'XPD', NULL, NULL, NULL, false, NULL, 0, '964', 167),
  ('currency', 'XPF', NULL, NULL, NULL, false, '₣', 0, '953', 168),
  ('currency', 'XPT', NULL, NULL, NULL, false, NULL, 0, '962', 169),
  ('currency', 'XSU', NULL, NULL, NULL, false, NULL, 0, '994', 170),
  ('currency', 'XTS', NULL, NULL, NULL, false, NULL, 0, '963', 171),
  ('currency', 'XUA', NULL, NULL, NULL, false, NULL, 0, '965', 172),
  ('currency', 'XXX', NULL, NULL, NULL, false, NULL, 0, '999', 173),
  ('currency', 'YER', NULL, NULL, NULL, false, '﷼', 2, '886', 174),
  ('currency', 'ZAR', NULL, NULL, NULL, false, 'R', 2, '710', 175),
  ('currency', 'ZMW', NULL, NULL, NULL, false, 'ZK', 2, '967', 176),
  ('currency', 'ZWG', NULL, NULL, NULL, false, 'ZiG', 2, '924', 177)
ON CONFLICT (type, code) DO NOTHING;
